name: shutter_analytics_service
author: isotrop
version: 0.1.0
description: A demonstration of a simple service
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeifxoyvybijxyc3ifplzqthsd7fvozxvcd2kmfkxqf7gmcgt7olzza
fingerprint_ignore_patterns: []
agent: valory/shutter_analytics_agent:0.1.0
number_of_agents: 1
deployment: {}
---
public_id: isotrop/shutter_analytics_agent:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/benchmarks}
  params:
    args:
      service_registry_address: ${str:null}
      share_tm_config_on_startup: ${bool:false}
      on_chain_service_id: ${int:null}
      setup:
        all_participants: ${list:["0x0000000000000000000000000000000000000000"]}
        safe_contract_address: ${str:'0x0000000000000000000000000000000000000000'}
        consensus_threshold: ${int:null}
      tendermint_url: ${str:http://localhost:26657}
      tendermint_com_url: ${str:http://localhost:8080}
      log_path: ${str:/mnt/d/workspace/shutter-analytics-agent/shutter-mev/logs/}
      api: ${str:http://172.31.112.1:3000/logs}
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: isotrop/shutter_analytics_agent:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    gnosis:
      address: ${GNOSIS_LEDGER_RPC:str:http://host.docker.internal:8545}
      chain_id: ${GNOSIS_LEDGER_CHAIN_ID:int:42220}
      poa_chain: ${GNOSIS_LEDGER_IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${GNOSIS_LEDGER_PRICING:str:eip1559}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${ACN_URI:str:acn.staging.autonolas.tech:9005}
    public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
